# MLHyperparameterTuning  Pipeline
#
# A Github Service Connection must also be created with the name "AIArchitecturesAndPractices-GitHub"

resources:
  repositories:
    - repository: aitemplates
      type: github
      name: microsoft/AI
      endpoint: AIArchitecturesAndPractices-GitHub

trigger: none

pr: none

stages:
- template: .ci/stages/deploy_notebooks_stages_v2.yml@aitemplates
  parameters:
    jobDisplayName: ADOTrainDeployJob
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    workload_vars: ../vars/mlhyperparametertuning_vars.yml
