# MLHyperparameterTuning  Pipeline
#
# A Github Service Connection must also be created with the name "AIArchitecturesAndPractices-GitHub"

resources:
  repositories:
    - repository: aitemplates
      type: github
      name: microsoft/AI
      endpoint: AIArchitecturesAndPractices-GitHub

trigger: none

pr: none

stages:
- template: .ci/stages/deploy_notebooks_stages_v2.yml@aitemplates
  parameters:
    Agent: $(Agent_Name)
    jobDisplayName: ADOTrainDeployJob
    DefaultWorkingDirectory: $(System.DefaultWorkingDirectory)
    workload_vars: ../vars/ado_ml_batch_train_vars.yml
    flighting_release: false
    flighting_preview: false
    sql_server_name: $(sql_server_name)
    sql_database_name: $(sql_database_name)
    sql_username: $(sql_username)
    sql_password: $(sql_password)
    TestPostfix: coalesce($(TestPostfix),-$(Build.SourceBranchName))
    data_prep: coalesce($(data_prep),'true')
    train: coalesce($(train),'true')
